site:
  title: MSI/MSIX Generator
  url: https://dev-centr.github.io/msi-generator
  start_page: msi-generator::index.adoc
output:
  dir: ./public
content:
  sources:
    - url: .
      branches: [HEAD]
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./docs/supplemental-ui

